language: cpp

matrix:
  include:
    - os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
      env:
        - MATRIX_EVAL="CXX=g++-8"
    - os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - llvm-toolchain-xenial-7
          packages:
            - clang-7
      env:
        - MATRIX_EVAL="CXX=clang++-7"

branches:
  only:
    - master

before_install:
  - eval "${MATRIX_EVAL}"

notifications:
  email: false
